[[ACCOUNTS]]
address = "rGCtayZogyWdKj8GAUgGSURd2ThfcyBQhP"
network = "main"

[[CURRENCIES]]
code = "1CELL"
issuer = "rGCtayZogyWdKj8GAUgGSURd2ThfcyBQhP"
network = "main"
icon = "https://orangecat-xrpl.github.io/gato.jpg"
